### ISSUE TITLE
Vision encoding

### ISSUE THREAD

**Issue by terkelg** [rchatham/OpenAI.swift#2]
I tested your library and used the GPT-4 Vision example from the readme. However, it encodes to an invalid JSON schema, that wraps the image object in an extra `_0` object, causing OpenAI to respond with a 400 error

JSON:
```javascript
    {
      "role" : "user",
      "content" : [
        {
          "image" : {
            "_0" : { // <---
              "type" : "image_url",
              "image_url" : {
                "detail" : "auto",
                "url" : "data:image\/jpeg;base64,\/9j\/4AAQSkZJRgAAAABAAAAGgAAAAAAA..."
              }
            }
          }
        }
      ]
    }
```

**Comment by rchatham** [comment]
Hey @terkelg, thanks for reporting this. Sorry for not getting back to you sooner. I hadn't fully tested this yet myself but will try to get a fix up soon.

**Comment by rchatham** [comment]
Hi @terkelg, I pushed a fix which resolved the issue and adds a test to cover it with commit 5264097f752360b867771efb857228dcffaed24b
