### ISSUE TITLE
Missing platforms field in package.swift

### ISSUE THREAD

**Issue by terkelg** [rchatham/OpenAI.swift#6]
The `Package.swift` file does not specify the minimum required platform versions. I had to clone the project locally and add the following before my project could compile. It would be great if I could use it directly without this step 🙏 

```swift
  platforms: [
    .macOS(.v13),
    .iOS(.v16),
    .watchOS(.v8)
  ]
```

**Comment by rchatham** [comment]
Thanks for the lookout @terkelg! Updated 85bb81ec04b94888ae5aed7e9685a37e5e8ab622 🏎️ 😄
